# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool: mypool

variables:
  buildConfiguration: 'Release'
  buildPlatform: 'any cpu'

steps:
- task: SonarCloudPrepare@1
  inputs:
    SonarCloud: 'sonarcloud'
    organization: 'ahmedmarmouch'
    scannerMode: 'MSBuild'
    projectKey: 'ahmedmarmouch_elite'
    projectName: 'elite'


- task: SonarCloudAnalyze@1
  displayName: 'Run SonarCloud analysis'

- task: SonarCloudPublish@1
  displayName: 'Publish results on build summary'